version: '3'

services:
  my-home-database:
    image: postgres:10.0
    container_name: my-home-database
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - 5432:5432
    volumes:
      - myHomeDatabaseData:/var/lib/postgresql/data
    networks:
      - rf_network

  my-home-backend:
    image: amazoncorretto:11.0.4
    container_name: my-home-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-home-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${postgres_password}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - 8080:8080
    depends_on:
      - my-home-database
    volumes:
      - ./my-home-backend/target/my-home-backend-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - rf_network

  my-home-web:
    image: nginx:alpine
    container_name: my-home-web
    ports:
      - 80:80
    depends_on:
      - my-home-backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./my-home-web/dist/my-home-web/:/usr/share/nginx/html
    networks:
      - rf_network


volumes:
  myHomeDatabaseData:

networks:
  rf_network:
    external: true
